/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.4/userguide/building_java_projects.html in the Gradle documentation.
 */

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

plugins {
    `maven-publish` // pour publication du jar dans un repository Maven
    alias(libs.plugins.kotlin.jvm)

    id("org.openapi.generator") version "7.19.0" // Contract first plugin
    id("org.springframework.boot") version "4.0.2" // To treat this module as a Spring Boot app
    id("io.spring.dependency-management") version "1.1.7" // Spring Boot dependencies manager

    // Kotlin plugin that makes classes annotated with Spring annotations 'open'
    id("org.jetbrains.kotlin.plugin.spring") version "2.3.10"
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.boot:spring-boot-dependencies:4.0.2")
    }
}

dependencies {
    /* Spring boot */
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-actuator")

    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.1")

    // Jackson Kotlin module
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    // Kotlin reflection (aligned with Kotlin plugin version)
    implementation("org.jetbrains.kotlin:kotlin-reflect")

    /* Testing */
    testImplementation(libs.junit.jupiter) // Use JUnit Jupiter for testing.
    testImplementation("org.springframework.boot:spring-boot-starter-test") // Spring Boot test support
    testImplementation("org.mockito.kotlin:mockito-kotlin:4.1.0")  // Mockito Kotlin (modern artifact)
    testImplementation("org.assertj:assertj-core:3.27.7") // AssertJ for fluent assertions
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

sourceSets {
    main {
        kotlin.srcDir("${rootProject.layout.buildDirectory.get().asFile}/generated/openapi/src/main/kotlin")
    }
}

openApiGenerate {
    generatorName.set("kotlin-spring")
    inputSpec.set("$rootDir/app/src/main/resources/super-heroes.api.spec.yaml")

    outputDir.set("${rootProject.layout.buildDirectory.get().asFile}/generated/openapi")

    apiPackage.set("com.spring.boot.swagger.generated.api")
    modelPackage.set("com.spring.boot.swagger.generated.model")
    invokerPackage.set("com.spring.boot.swagger.generated.invoker")

    configOptions.set(
        mapOf(
            "useSpringBoot3" to "true",
            "useTags" to "true",
            "interfaceOnly" to "false",
            "delegatePattern" to "true"
        )
    )
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

/*tasks.openApiGenerate {
    doFirst {
        delete(layout.buildDirectory.dir("generated/openapi").map { it.asFile.path })
    }
}*/
tasks.compileKotlin {
    dependsOn(tasks.openApiGenerate)
}
